Repository Lipoic/Lipoic-Backend, pull requests merged in 2022-10, with the labels that each got.

#10 feat: auth and user api
  .env.example
  .eslintrc.js
  .github/workflows/test.yml
  .gitignore
  .vscode/extensions.json
  README.md
  assets/verify_email/en-US.html
  assets/verify_email/zh-CN.html
  assets/verify_email/zh-TW.html
  package.json
  src/custom.d.ts
  src/database/index.ts
  src/index.ts
  src/model/auth/connect_account.ts
  src/model/auth/user.ts
  src/model/auth/user_locale.ts
  src/model/auth/user_mode.ts
  src/model/lesson/lesson.ts
  src/model/lesson/lesson_permission.ts
  src/router/api/authentication/index.ts
  src/router/api/authentication/oauth_access_info.ts
  src/router/api/authentication/oauth_data.ts
  src/router/api/authentication/util.ts
  src/router/api/index.ts
  src/router/api/user/data.d.ts
  src/router/api/user/index.ts
  src/router/api/user/util.ts
  src/router/index.ts
  src/router/util/code.ts
  src/router/util/response.ts
  src/router/util/util.ts
  src/util/email.ts
  src/util/init.ts
  src/util/jwt.ts
  src/util/server.ts
  src/util/swagger.ts
  test/database/database.test.ts
  test/global_setup.ts
  test/router/api/authentication/authentication_api.test.ts
  test/router/api/authentication/oauth_data.test.ts
  test/router/api/user/user_api.test.ts
  test/router/api/user/user_util.test.ts
  test/router/router.test.ts
  test/util/jwt.test.ts
  tsconfig.json
  vitest.config.ts
  yarn.lock
Labels: documentation, enhancement

#11 feat: docker
  .dockerignore
  Dockerfile
  README.md
  docker-compose.yml
  script/deploy.sh
  script/gen_ecdsa_key.sh
Labels: enhancement

#12 fix: Wrong operator usage
  src/index.ts
Labels: fix bug

#13 fix: Failed to generate API docs when executing with docker
  .github/workflows/pull_request.yml
  .gitignore
  Dockerfile
  README.md
  package.json
  src/index.ts
  src/model/auth/user.ts
  src/types.d.ts
  src/util/server.ts
  src/util/swagger.ts
  test/router/router.test.ts
  tsconfig.json
  vitest.config.ts
  yarn.lock
Labels: fix bug

#15 Fix getting the current user information missing email and connect accounts fields. (#14)
  src/model/auth/user.ts
  src/router/api/user/index.ts
  src/util/swagger.ts
  test/router/api/user/user_api.test.ts
Labels: fix bug

#16 feat: controller init
  src/router/api/authentication/controller.ts
  src/router/api/authentication/index.ts
  src/router/api/index.ts
  src/router/api/user/controller.ts
  src/router/api/user/data.d.ts
  src/router/api/user/index.ts
  src/router/util/code.ts
Labels: enhancement
